export const UPDATE_BOARD = "UPDATE_BOARD";
export const ADD_COLUMN = "ADD_COLUMN";
export const ADD_TASK = "ADD_TASK";

export const OPEN_TASK_MODAL = "OPEN_TASK_MODAL";
export const CLOSE_TASK_MODAL = "CLOSE_TASK_MODAL";
export const OPEN_DELETE_MODAL = "OPEN_DELETE_MODAL";
export const CLOSE_DELETE_MODAL = "CLOSE_DELETE_MODAL";

export const TOGGLE_STATUS = "TOGGLE_STATUS";
export const ADD_NEW_COMMENT = "ADD_NEW_COMMENT";

export const UPDATE_COLUMN_TITLE = "UPDATE_COLUMN_TITLE";
export const UPDATE_TASK_DETAILS = "UPDATE_TASK_DETAILS";

export const DELETE_COLUMN = "DELETE_COLUMN";
export const DELETE_TASK = "DELETE_TASK";
